# Generated by Django 6.0.3.dev20260206153216 on 2026-04-28 11:46

import django.db.models.deletion
import finder.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoAppModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', finder.models.fields.FinderFileField(accept_mime_types=['image/*'], ambit='public', blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, verbose_name='Demo File')),
                ('folder', finder.models.fields.FinderFolderField(ambit='public', blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, verbose_name='Demo Folder')),
            ],
        ),
    ]
