# Generated by Django 5.2.dev20241203005448 on 2025-01-03 08:36

import finder.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoAppModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', finder.models.fields.FinderFileField(blank=True, null=True, verbose_name='Demo File')),
            ],
        ),
    ]
