"""Tests for filer.utils.filer_easy_thumbnails."""

from django.core.files.storage import FileSystemStorage
from django.test import TestCase, override_settings

from filer.storage import PrivateFileSystemStorage, PublicFileSystemStorage
from filer.utils.filer_easy_thumbnails import (
    FilerThumbnailer,
    original_filename_candidates,
    thumbnail_to_original_filename,
)


def custom_namer(thumbnailer, source_filename, thumbnail_extension, **kwargs):
    return f'custom_prefix_{source_filename}.{thumbnail_extension}'


class ThumbnailToOriginalFilenameTests(TestCase):
    """Tests for thumbnail_to_original_filename."""

    def test_default_namer_scheme(self):
        result = thumbnail_to_original_filename('path/to/file.jpg.100x100_q85.jpg')
        self.assertEqual(result, 'path/to/file.jpg')

    def test_legacy_scheme(self):
        """Thumbnails generated by filer < 3.6 use a ``__`` delimiter."""
        result = thumbnail_to_original_filename('path/to/file.jpg__100x100_q85.jpg')
        self.assertEqual(result, 'path/to/file.jpg')

    def test_without_delimiter(self):
        result = thumbnail_to_original_filename('file.jpg')
        self.assertIsNone(result)

    def test_multiple_delimiters(self):
        # The options part of the name always starts with the size
        result = thumbnail_to_original_filename('a__b__100x100.jpg')
        self.assertEqual(result, 'a__b')

    def test_double_underscore_in_source_filename(self):
        """A ``__`` in the source file name is not mistaken for the delimiter."""
        result = thumbnail_to_original_filename('a__b.jpg.100x100_q85_crop.jpg')
        self.assertEqual(result, 'a__b.jpg')

    def test_legacy_name_with_dotted_option_value(self):
        """The old namer emitted option values verbatim, dots included."""
        result = thumbnail_to_original_filename(
            'foo.jpg__200x200_q85_subject_location-0.5,0.5.jpg')
        self.assertEqual(result, 'foo.jpg')

    def test_name_with_dotted_option_value(self):
        result = thumbnail_to_original_filename(
            'foo.jpg.200x200_q85_subject_location-0.5,0.5.jpg')
        self.assertEqual(result, 'foo.jpg')

    def test_size_like_double_underscore_in_source_filename(self):
        """The current scheme wins over a legacy read of the source filename."""
        result = thumbnail_to_original_filename('a__100x100_x.jpg.50x50_q85.jpg')
        self.assertEqual(result, 'a__100x100_x.jpg')

    def test_candidates_cover_both_schemes(self):
        self.assertEqual(
            list(original_filename_candidates('file.jpg__100x100_q85.jpg')),
            ['file.jpg'],
        )
        self.assertEqual(
            list(original_filename_candidates('file.jpg.100x100_q85.jpg')),
            ['file.jpg'],
        )
        self.assertEqual(list(original_filename_candidates('file.jpg')), [])


class ThumbnailerNameMixinTests(TestCase):
    """Tests for ThumbnailerNameMixin.get_thumbnail_name."""

    def make_thumbnailer(self, name='uploads/test_image.png', **kwargs):
        kwargs.setdefault('is_public', True)
        return FilerThumbnailer(file=None, name=name, **kwargs)

    def test_basic_thumbnail_name(self):
        name = self.make_thumbnailer().get_thumbnail_name({'size': (100, 100), 'crop': True})
        self.assertEqual(name, 'uploads/test_image.png.100x100_q85_crop.jpg')

    def test_svg_preserves_extension(self):
        """SVG sources are written as SVG, so the name must stay ``.svg``."""
        thumbnailer = self.make_thumbnailer(name='uploads/icon.svg')
        name = thumbnailer.get_thumbnail_name({'size': (50, 50)})
        self.assertEqual(name, 'uploads/icon.svg.50x50_q85.svg')

    def test_svg_preserves_extension_when_transparent(self):
        thumbnailer = self.make_thumbnailer(name='uploads/icon.svg')
        name = thumbnailer.get_thumbnail_name({'size': (50, 50)}, transparent=True)
        self.assertTrue(name.endswith('.svg'))

    def test_svg_preserves_extension_for_private_files(self):
        thumbnailer = self.make_thumbnailer(name='uploads/icon.svg', is_public=False)
        name = thumbnailer.get_thumbnail_name({'size': (50, 50)})
        self.assertTrue(name.endswith('.svg'))

    def test_naming_options_are_restored(self):
        """The temporary namer/extension overrides do not leak."""
        thumbnailer = self.make_thumbnailer(name='uploads/icon.svg', is_public=False)
        namer, preserve = thumbnailer.thumbnail_namer, thumbnailer.thumbnail_preserve_extensions
        thumbnailer.get_thumbnail_name({'size': (50, 50)})
        self.assertIs(thumbnailer.thumbnail_namer, namer)
        self.assertEqual(thumbnailer.thumbnail_preserve_extensions, preserve)

    def test_naming_options_are_restored_on_error(self):
        """A file without a name must not leave the default namer behind."""
        thumbnailer = self.make_thumbnailer(name=None, is_public=False)
        namer = thumbnailer.thumbnail_namer
        with self.assertRaises(Exception):
            thumbnailer.get_thumbnail_name({'size': (50, 50)})
        self.assertIs(thumbnailer.thumbnail_namer, namer)

    def test_transparent_preserves_png(self):
        name = self.make_thumbnailer().get_thumbnail_name({'size': (100, 100)}, transparent=True)
        self.assertTrue(name.endswith('.png'))

    @override_settings(THUMBNAIL_PRESERVE_EXTENSIONS=['png'])
    def test_preserve_extensions_list(self):
        name = self.make_thumbnailer(name='uploads/image.png').get_thumbnail_name({'size': (100, 100)})
        self.assertTrue(name.endswith('.png'))

    def test_subdir_and_prefix(self):
        thumbnailer = self.make_thumbnailer(name='uploads/photo.jpg', thumbnail_basedir='basedir')
        thumbnailer.thumbnail_subdir = 'subdir'
        name = thumbnailer.get_thumbnail_name({'size': (100, 100)})
        self.assertTrue(name.startswith('basedir/uploads/subdir/'))

    def test_quality_in_filename_for_jpg(self):
        name = self.make_thumbnailer().get_thumbnail_name({'size': (100, 100)})
        self.assertIn('q85', name)


@override_settings(THUMBNAIL_NAMER='tests.test_filer_easy_thumbnails.custom_namer')
class ThumbnailNamerSelectionTests(TestCase):
    """Public files honour ``THUMBNAIL_NAMER``, private files never do."""

    def make_thumbnailer(self, **kwargs):
        return FilerThumbnailer(file=None, name='uploads/photo.jpg', **kwargs)

    def test_public_file_uses_custom_namer(self):
        name = self.make_thumbnailer(is_public=True).get_thumbnail_name({'size': (100, 100)})
        self.assertEqual(name, 'uploads/custom_prefix_photo.jpg.jpg')

    def test_private_file_uses_default_namer(self):
        name = self.make_thumbnailer(is_public=False).get_thumbnail_name({'size': (100, 100)})
        self.assertEqual(name, 'uploads/photo.jpg.100x100_q85.jpg')
        self.assertEqual(thumbnail_to_original_filename(name), 'uploads/photo.jpg')

    def test_falls_back_on_secure_storage_flag(self):
        """Without an explicit flag the thumbnail storage decides."""
        private = self.make_thumbnailer(thumbnail_storage=PrivateFileSystemStorage())
        self.assertFalse(private.is_public_thumbnail())
        self.assertEqual(
            private.get_thumbnail_name({'size': (100, 100)}),
            'uploads/photo.jpg.100x100_q85.jpg',
        )

        public = self.make_thumbnailer(thumbnail_storage=PublicFileSystemStorage())
        self.assertTrue(public.is_public_thumbnail())
        self.assertEqual(
            public.get_thumbnail_name({'size': (100, 100)}),
            'uploads/custom_prefix_photo.jpg.jpg',
        )

    def test_unknown_storage_is_treated_as_private(self):
        """Fail safe: an unnamable thumbnail is worse than an unstyled name."""
        thumbnailer = self.make_thumbnailer(thumbnail_storage=FileSystemStorage())
        self.assertFalse(thumbnailer.is_public_thumbnail())
        self.assertEqual(
            thumbnailer.get_thumbnail_name({'size': (100, 100)}),
            'uploads/photo.jpg.100x100_q85.jpg',
        )
