# Generated by Django 4.1.9 on 2023-06-13 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0015_alter_file_owner_alter_file_polymorphic_ctype_and_more'),
        ('custom_image', '0003_auto_20180414_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s_file', serialize=False, to='filer.file'),
        ),
        migrations.AddField(
            model_name='image',
            name='_transparent',
            field=models.BooleanField(default=False),
        ),
    ]
