import os
import re
from contextlib import contextmanager

from easy_thumbnails.files import Thumbnailer
from easy_thumbnails.namers import default


#: Naming scheme of filer < 3.6: ``source.jpg__100x100_q85_crop.jpg``
RE_LEGACY_THUMBNAIL_NAME = re.compile(r"^(?P<source_filename>.+)__\d+x\d+.*\.[^.]+$")
#: easy-thumbnails' default namer: ``source.jpg.100x100_q85_crop.jpg``
RE_THUMBNAIL_NAME = re.compile(r"^(?P<source_filename>.+)\.\d+x\d+.*\.[^.]+$")


def original_filename_candidates(thumbnail_name):
    """
    Yield the source file names ``thumbnail_name`` may have been generated from,
    most likely candidate first.

    Thumbnails of private files are always named by easy-thumbnails' default
    namer, but thumbnails generated by filer < 3.6 are still around and use
    filer's own ``__`` delimiter. Both schemes start the options part of the
    name with ``<width>x<height>``, which is what tells them apart. The current
    scheme is tried first: a source file name that itself contains ``__`` can
    otherwise be cut short by the legacy pattern.
    """
    match = RE_THUMBNAIL_NAME.match(thumbnail_name)
    if match:
        yield match.group("source_filename")
    match = RE_LEGACY_THUMBNAIL_NAME.match(thumbnail_name)
    if match:
        yield match.group("source_filename")


def thumbnail_to_original_filename(thumbnail_name):
    return next(original_filename_candidates(thumbnail_name), None)


class ThumbnailerNameMixin:
    thumbnail_basedir = ''
    thumbnail_subdir = ''
    thumbnail_prefix = ''

    #: ``True``/``False`` if the creator of the thumbnailer knows whether the
    #: source file is public. ``None`` means "work it out from the file".
    source_is_public = None

    def is_public_thumbnail(self):
        """Is the source file of this thumbnailer publicly served?"""
        if self.source_is_public is not None:
            return self.source_is_public
        instance = getattr(self, 'instance', None)
        if instance is not None and hasattr(instance, 'is_public'):
            # ``MultiStorageFieldFile``: ask the filer ``File`` it belongs to.
            return instance.is_public
        # Last resort: filer's own storage classes flag themselves as (in)secure.
        # Default to private: naming a public file the private way merely ignores
        # ``THUMBNAIL_NAMER``, while the opposite mistake makes every thumbnail of
        # that file unservable.
        return not getattr(getattr(self, 'thumbnail_storage', None), 'is_secure', True)

    @contextmanager
    def _naming_options(self):
        namer = self.thumbnail_namer
        preserve_extensions = self.thumbnail_preserve_extensions
        try:
            if not self.is_public_thumbnail():
                # Names of private thumbnails have to be reversible into the name
                # of their source file (see ``thumbnail_to_original_filename``), so
                # that ``filer.server.views.serve_protected_thumbnail`` can check
                # the permissions of that source file. Ignore ``THUMBNAIL_NAMER``.
                self.thumbnail_namer = default
            if os.path.splitext(self.name or '')[1][1:].lower() == 'svg':
                # ``Thumbnailer.generate_thumbnail`` writes SVG sources as SVG, so
                # the name must keep the ``.svg`` extension no matter what
                # ``THUMBNAIL_EXTENSION`` says.
                self.thumbnail_preserve_extensions = True
            yield
        finally:
            self.thumbnail_namer = namer
            self.thumbnail_preserve_extensions = preserve_extensions

    def get_thumbnail_name(self, thumbnail_options, transparent=False):
        """
        A version of ``Thumbnailer.get_thumbnail_name`` that keeps the extension
        of SVG sources and that forces the default namer for private files.
        """
        with self._naming_options():
            return super().get_thumbnail_name(thumbnail_options, transparent)


class ActionThumbnailerMixin:
    thumbnail_basedir = ''
    thumbnail_subdir = ''
    thumbnail_prefix = ''

    def get_thumbnail_name(self, thumbnail_options, transparent=False):
        """
        A version of ``Thumbnailer.get_thumbnail_name`` that returns the original
        filename to resize.
        """
        path, filename = os.path.split(self.name)

        basedir = self.thumbnail_basedir
        subdir = self.thumbnail_subdir

        return os.path.join(basedir, path, subdir, filename)

    def thumbnail_exists(self, thumbnail_name):
        return False


class FilerThumbnailer(ThumbnailerNameMixin, Thumbnailer):
    def __init__(self, *args, **kwargs):
        self.thumbnail_basedir = kwargs.pop('thumbnail_basedir', '')
        self.source_is_public = kwargs.pop('is_public', None)
        super().__init__(*args, **kwargs)


class FilerActionThumbnailer(ActionThumbnailerMixin, Thumbnailer):
    pass
