# Generated by Django 4.2.15 on 2024-10-26 08:46

from django.db import migrations, models
import finder.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestAppModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', finder.models.fields.FinderFileField(blank=True, null=True, verbose_name='Demo File')),
            ],
        ),
    ]
