# Generated by Django 6.0.3.dev20260206153216 on 2026-05-14 15:16

import django.db.models.deletion
import finder.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleAppModel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', finder.models.fields.FinderFileField(ambit='public', blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.PROTECT)),
            ],
        ),
        migrations.CreateModel(
            name='SampleAppModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', finder.models.fields.FinderFileField(ambit='public', blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.SET_DEFAULT)),
            ],
        ),
        migrations.CreateModel(
            name='SampleAppModel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', finder.models.fields.FinderFileField(accept_mime_types=['image/*'], ambit='public', blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.CASCADE)),
            ],
        ),
        migrations.CreateModel(
            name='SampleAppModel4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', finder.models.fields.FinderFolderField(ambit='public', blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.PROTECT)),
            ],
        ),
        migrations.CreateModel(
            name='SampleAppModel5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', finder.models.fields.FinderFolderField(ambit='public', blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.SET_DEFAULT)),
            ],
        ),
        migrations.CreateModel(
            name='SampleAppModel6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', finder.models.fields.FinderFolderField(ambit='public', blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.CASCADE)),
            ],
        ),
    ]
