# Generated by Django 5.2.17 on 2026-09-03 11:54

import django.db.models.deletion
import finder.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleAppModel7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', finder.models.fields.FinderFileField(ambit='public', blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.SET_NULL)),
            ],
        ),
        migrations.CreateModel(
            name='SampleAppModel8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', finder.models.fields.FinderFileField(ambit='public', blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING)),
            ],
        ),
        migrations.CreateModel(
            name='SampleAppModel9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', finder.models.fields.FinderFileField(ambit='public', blank=True, db_index=True, null=True, on_delete=models.SET(uuid.UUID('00000000-0000-0000-0000-0000000000ff')))),
            ],
        ),
    ]
