# Generated by Django 5.2.dev20250107082209 on 2026-02-05 10:05

import django.db.models.deletion
import finder.models.file
import finder.models.inode
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, validators=[finder.models.inode.filename_validator], verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('ordering', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Ordering index')),
                ('meta_data', models.JSONField(blank=True, default=dict)),
                ('file_name', models.CharField(editable=False, max_length=255, verbose_name='File name')),
                ('file_size', models.BigIntegerField(editable=False, verbose_name='Size')),
                ('sha1', models.CharField(blank=True, default='', editable=False, max_length=40, verbose_name='SHA1-hash')),
                ('mime_type', models.CharField(db_index=True, default='application/octet-stream', editable=False, help_text='MIME-type of uploaded content', max_length=255, validators=[finder.models.file.mimetype_validator], verbose_name='MIME-type')),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'abstract': False,
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ArchiveModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('finder.filemodel',),
        ),
        migrations.CreateModel(
            name='AudioFileModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('finder.filemodel',),
        ),
        migrations.CreateModel(
            name='PDFFileModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('finder.filemodel',),
        ),
        migrations.CreateModel(
            name='SpreadsheetModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('finder.filemodel',),
        ),
        migrations.CreateModel(
            name='VideoFileModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('finder.filemodel',),
        ),
        migrations.CreateModel(
            name='FolderModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, validators=[finder.models.inode.filename_validator], verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('ordering', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Ordering index')),
                ('meta_data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('parent', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finder.foldermodel', verbose_name='Folder')),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
                'default_permissions': [],
            },
        ),
        migrations.AddField(
            model_name='filemodel',
            name='parent',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finder.foldermodel', verbose_name='Folder'),
        ),
        migrations.CreateModel(
            name='DiscardedInode',
            fields=[
                ('inode', models.UUIDField(primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Deleted at')),
                ('previous_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finder.foldermodel')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultAccessControlEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege', models.PositiveSmallIntegerField(choices=[(1, 'Read'), (2, 'Write (Dropbox)'), (3, 'Read & Write'), (4, 'Administrator'), (7, 'Full Control')], default=1)),
                ('everyone', models.BooleanField(default=False, verbose_name='Everyone')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_access_control_list', to='finder.foldermodel')),
            ],
            options={
                'verbose_name': 'Default Access Control Entry',
                'verbose_name_plural': 'Default Access Control Entries',
            },
        ),
        migrations.CreateModel(
            name='AmbitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('verbose_name', models.CharField(max_length=200)),
                ('admin_name', models.CharField(max_length=100, null=True)),
                ('_original_storage', models.CharField(default='finder_public')),
                ('_sample_storage', models.CharField(default='finder_public_samples')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
                ('root_folder', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ambit', to='finder.foldermodel')),
                ('trash_folders', models.ManyToManyField(editable=False, related_name='+', to='finder.foldermodel')),
            ],
        ),
        migrations.CreateModel(
            name='ImageFileModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, validators=[finder.models.inode.filename_validator], verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('ordering', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Ordering index')),
                ('meta_data', models.JSONField(blank=True, default=dict)),
                ('file_name', models.CharField(editable=False, max_length=255, verbose_name='File name')),
                ('file_size', models.BigIntegerField(editable=False, verbose_name='Size')),
                ('sha1', models.CharField(blank=True, default='', editable=False, max_length=40, verbose_name='SHA1-hash')),
                ('mime_type', models.CharField(db_index=True, default='application/octet-stream', editable=False, help_text='MIME-type of uploaded content', max_length=255, validators=[finder.models.file.mimetype_validator], verbose_name='MIME-type')),
                ('width', models.SmallIntegerField(default=0)),
                ('height', models.SmallIntegerField(default=0)),
                ('crop_x', models.FloatField(blank=True, null=True)),
                ('crop_y', models.FloatField(blank=True, null=True)),
                ('crop_size', models.FloatField(blank=True, null=True)),
                ('gravity', models.CharField(blank=True, choices=[('', 'Center'), ('n', 'North'), ('ne', 'Northeast'), ('e', 'East'), ('se', 'Southeast'), ('s', 'South'), ('sw', 'Southwest'), ('w', 'West'), ('nw', 'Northwest')], default='', max_length=2)),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('parent', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finder.foldermodel', verbose_name='Folder')),
            ],
            options={
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='PILImageModel',
            fields=[
            ],
            options={
                'verbose_name': 'Web Image',
                'verbose_name_plural': 'Web Images',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('finder.imagefilemodel',),
        ),
        migrations.CreateModel(
            name='SVGImageModel',
            fields=[
            ],
            options={
                'verbose_name': 'SVG Image',
                'verbose_name_plural': 'SVG Images',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('finder.imagefilemodel',),
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='Color')),
                ('ambit', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='finder.ambitmodel')),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labels',
            },
        ),
        migrations.AddField(
            model_name='imagefilemodel',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='+', to='finder.label', verbose_name='Labels'),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='+', to='finder.label', verbose_name='Labels'),
        ),
        migrations.CreateModel(
            name='PinnedFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('ambit', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finder.ambitmodel')),
                ('folder', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pinned_folders', to='finder.foldermodel')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pinned Folder',
                'verbose_name_plural': 'Pinned Folders',
            },
        ),
        migrations.CreateModel(
            name='AccessControlEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege', models.PositiveSmallIntegerField(choices=[(1, 'Read'), (2, 'Write (Dropbox)'), (3, 'Read & Write'), (4, 'Administrator'), (7, 'Full Control')], default=1)),
                ('everyone', models.BooleanField(default=False, verbose_name='Everyone')),
                ('inode', models.UUIDField(db_index=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Control Entry',
                'verbose_name_plural': 'Access Control Entries',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('group__isnull', True), ('everyone', False)), models.Q(('user__isnull', True), ('group__isnull', False), ('everyone', False)), models.Q(('user__isnull', True), ('group__isnull', True), ('everyone', True)), _connector='OR'), name='acl_single_principal'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('inode', 'user'), name='acl_inode_user_unique'), models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('inode', 'group'), name='acl_inode_group_unique'), models.UniqueConstraint(condition=models.Q(('everyone', True)), fields=('inode',), name='acl_inode_everyone_unique'), models.CheckConstraint(condition=models.Q(('privilege__in', [1, 2, 3, 7])), name='acl_valid_privilege')],
            },
        ),
        migrations.AddConstraint(
            model_name='foldermodel',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_subfolder'),
        ),
        migrations.AddConstraint(
            model_name='defaultaccesscontrolentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('group__isnull', True), ('everyone', False)), models.Q(('user__isnull', True), ('group__isnull', False), ('everyone', False)), models.Q(('user__isnull', True), ('group__isnull', True), ('everyone', True)), _connector='OR'), name='dacl_single_principal'),
        ),
        migrations.AddConstraint(
            model_name='defaultaccesscontrolentry',
            constraint=models.CheckConstraint(condition=models.Q(('privilege__in', [1, 2, 3, 7])), name='dacl_valid_privilege'),
        ),
        migrations.AddConstraint(
            model_name='pinnedfolder',
            constraint=models.UniqueConstraint(fields=('owner', 'folder'), name='unique_pinned_folder'),
        ),
    ]
