# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-14 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderpermission',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='filer_folder_permission_groups', to='auth.Group', verbose_name='groups'),
        ),
    ]
