# Generated by Django 3.2.13 on 2022-07-22 15:20

from django.db import migrations
import filer.models.filemodels


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0015_alter_file_owner_alter_file_polymorphic_ctype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='canonical_url_slug',
            field=filer.models.filemodels.CanonicalUrlSlugField(blank=True, help_text='slug used to override canonical URL', max_length=255, null=True, unique=True, verbose_name='Canonical URL slug'),
        ),
    ]
