# Generated by Django 5.2.10 on 2026-01-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0017_image__transparent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'base_manager_name': 'objects', 'verbose_name': 'file', 'verbose_name_plural': 'files'},
        ),
    ]
