# Generated by Django 5.2.10 on 2026-09-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0018_alter_file_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='digital_source_type',
            field=models.CharField(blank=True, default='', editable=False, help_text="IPTC digital source type found in the image's metadata on upload, e.g., stating that it was created using generative AI.", max_length=255, verbose_name='digital source type'),
        ),
        migrations.AddField(
            model_name='image',
            name='has_content_credentials',
            field=models.BooleanField(default=False, editable=False, help_text='The uploaded image embeds C2PA Content Credentials. Their signature is not verified.', verbose_name='has content credentials'),
        ),
    ]
